all:
  vars:
    control_plane_endpoint: 10.10.10.110
    load_balancer_ip_pool:
      - 10.10.10.96/27
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 10.10.10.110, mac: '80:86:f2:18:55:b6', disk: nvme0n1, network_interface: enp0s31f6}
    workers:
      hosts:
        metal1: {ansible_host: 10.10.10.111, mac: '6c:4b:90:87:39:da', disk: nvme0n1, network_interface: enp0s31f6}
        # metal2: {ansible_host: 10.10.10.112, mac: '52:54:00:47:ed:ae', disk: vda, network_interface: enp1s0}
